use mml_DB;


/************************/
/*        INSERT        */
/************************/

-- INSERT GENRES --
INSERT INTO GENRE (id, name) VALUES (0, 'pop');
INSERT INTO GENRE (id, name) VALUES (0, 'dance pop');
INSERT INTO GENRE (id, name) VALUES (0, 'rap');
INSERT INTO GENRE (id, name) VALUES (0, 'pop rap');
INSERT INTO GENRE (id, name) VALUES (0, 'rock');
INSERT INTO GENRE (id, name) VALUES (0, 'latin');
INSERT INTO GENRE (id, name) VALUES (0, 'post-teen pop');
INSERT INTO GENRE (id, name) VALUES (0, 'hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'modern rock');
INSERT INTO GENRE (id, name) VALUES (0, 'trap');
INSERT INTO GENRE (id, name) VALUES (0, 'edm');
INSERT INTO GENRE (id, name) VALUES (0, 'reggaeton');
INSERT INTO GENRE (id, name) VALUES (0, 'pop rock');
INSERT INTO GENRE (id, name) VALUES (0, 'latin pop');
INSERT INTO GENRE (id, name) VALUES (0, 'tropical house');
INSERT INTO GENRE (id, name) VALUES (0, 'classic rock');
INSERT INTO GENRE (id, name) VALUES (0, 'southern hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'melodic rap');
INSERT INTO GENRE (id, name) VALUES (0, 'mellow gold');
INSERT INTO GENRE (id, name) VALUES (0, 'soft rock');
INSERT INTO GENRE (id, name) VALUES (0, 'electropop');
INSERT INTO GENRE (id, name) VALUES (0, 'album rock');
INSERT INTO GENRE (id, name) VALUES (0, 'indie pop');
INSERT INTO GENRE (id, name) VALUES (0, 'alternative metal');
INSERT INTO GENRE (id, name) VALUES (0, 'r&b');
INSERT INTO GENRE (id, name) VALUES (0, 'tropical');
INSERT INTO GENRE (id, name) VALUES (0, 'permanent wave');
INSERT INTO GENRE (id, name) VALUES (0, 'contemporary country');
INSERT INTO GENRE (id, name) VALUES (0, 'k-pop');
INSERT INTO GENRE (id, name) VALUES (0, 'urban contemporary');
INSERT INTO GENRE (id, name) VALUES (0, 'electro house');
INSERT INTO GENRE (id, name) VALUES (0, 'nu metal');
INSERT INTO GENRE (id, name) VALUES (0, 'hard rock');
INSERT INTO GENRE (id, name) VALUES (0, 'neo mellow');
INSERT INTO GENRE (id, name) VALUES (0, 'uk pop');
INSERT INTO GENRE (id, name) VALUES (0, 'alternative rock');
INSERT INTO GENRE (id, name) VALUES (0, 'canadian pop');
INSERT INTO GENRE (id, name) VALUES (0, 'folk rock');
INSERT INTO GENRE (id, name) VALUES (0, 'country');
INSERT INTO GENRE (id, name) VALUES (0, 'pop punk');
INSERT INTO GENRE (id, name) VALUES (0, 'rock en espanol');
INSERT INTO GENRE (id, name) VALUES (0, 'viral pop');
INSERT INTO GENRE (id, name) VALUES (0, 'grupera');
INSERT INTO GENRE (id, name) VALUES (0, 'german hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'gangster rap');
INSERT INTO GENRE (id, name) VALUES (0, 'country road');
INSERT INTO GENRE (id, name) VALUES (0, 'atl hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'underground hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'trap latino');
INSERT INTO GENRE (id, name) VALUES (0, 'regional mexican');
INSERT INTO GENRE (id, name) VALUES (0, 'alternative r&b');
INSERT INTO GENRE (id, name) VALUES (0, 'latin hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'dance rock');
INSERT INTO GENRE (id, name) VALUES (0, 'chicago rap');
INSERT INTO GENRE (id, name) VALUES (0, 'art rock');
INSERT INTO GENRE (id, name) VALUES (0, 'indie r&b');
INSERT INTO GENRE (id, name) VALUES (0, 'new wave pop');
INSERT INTO GENRE (id, name) VALUES (0, 'modern alternative rock');
INSERT INTO GENRE (id, name) VALUES (0, 'europop');
INSERT INTO GENRE (id, name) VALUES (0, 'indie rock');
INSERT INTO GENRE (id, name) VALUES (0, 'adult standards');
INSERT INTO GENRE (id, name) VALUES (0, 'reggaeton colombiano');
INSERT INTO GENRE (id, name) VALUES (0, 'french hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'banda');
INSERT INTO GENRE (id, name) VALUES (0, 'soul');
INSERT INTO GENRE (id, name) VALUES (0, 'emo rap');
INSERT INTO GENRE (id, name) VALUES (0, 'house');
INSERT INTO GENRE (id, name) VALUES (0, 'country rock');
INSERT INTO GENRE (id, name) VALUES (0, 'norteno');
INSERT INTO GENRE (id, name) VALUES (0, 'mexican pop');
INSERT INTO GENRE (id, name) VALUES (0, 'big room');
INSERT INTO GENRE (id, name) VALUES (0, 'latin alternative');
INSERT INTO GENRE (id, name) VALUES (0, 'pop urbaine');
INSERT INTO GENRE (id, name) VALUES (0, 'latin rock');
INSERT INTO GENRE (id, name) VALUES (0, 'nuevo regional mexicano');
INSERT INTO GENRE (id, name) VALUES (0, 'funk carioca');
INSERT INTO GENRE (id, name) VALUES (0, 'k-pop boy group');
INSERT INTO GENRE (id, name) VALUES (0, 'sertanejo universitario');
INSERT INTO GENRE (id, name) VALUES (0, 'indie folk');
INSERT INTO GENRE (id, name) VALUES (0, 'reggaeton flow');
INSERT INTO GENRE (id, name) VALUES (0, 'hip pop');
INSERT INTO GENRE (id, name) VALUES (0, 'neo soul');
INSERT INTO GENRE (id, name) VALUES (0, 'art pop');
INSERT INTO GENRE (id, name) VALUES (0, 'pop edm');
INSERT INTO GENRE (id, name) VALUES (0, 'j-pop');
INSERT INTO GENRE (id, name) VALUES (0, 'metal');
INSERT INTO GENRE (id, name) VALUES (0, 'latin arena pop');
INSERT INTO GENRE (id, name) VALUES (0, 'indie poptimism');
INSERT INTO GENRE (id, name) VALUES (0, 'spanish pop');
INSERT INTO GENRE (id, name) VALUES (0, 'post-grunge');
INSERT INTO GENRE (id, name) VALUES (0, 'stomp and holler');
INSERT INTO GENRE (id, name) VALUES (0, 'new wave');
INSERT INTO GENRE (id, name) VALUES (0, 'ranchera');
INSERT INTO GENRE (id, name) VALUES (0, 'boy band');
INSERT INTO GENRE (id, name) VALUES (0, 'folk');
INSERT INTO GENRE (id, name) VALUES (0, 'lo-fi beats');
INSERT INTO GENRE (id, name) VALUES (0, 'psychedelic rock');
INSERT INTO GENRE (id, name) VALUES (0, 'funk');
INSERT INTO GENRE (id, name) VALUES (0, 'colombian pop');
INSERT INTO GENRE (id, name) VALUES (0, 'roots rock');
INSERT INTO GENRE (id, name) VALUES (0, 'singer-songwriter');
INSERT INTO GENRE (id, name) VALUES (0, 'miami hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'indie soul');
INSERT INTO GENRE (id, name) VALUES (0, 'progressive house');
INSERT INTO GENRE (id, name) VALUES (0, 'blues rock');
INSERT INTO GENRE (id, name) VALUES (0, 'german pop');
INSERT INTO GENRE (id, name) VALUES (0, 'canadian hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'quiet storm');
INSERT INTO GENRE (id, name) VALUES (0, 'conscious hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'modern country rock');
INSERT INTO GENRE (id, name) VALUES (0, 'motown');
INSERT INTO GENRE (id, name) VALUES (0, 'new romantic');
INSERT INTO GENRE (id, name) VALUES (0, 'italian hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'desi pop');
INSERT INTO GENRE (id, name) VALUES (0, 'vapor trap');
INSERT INTO GENRE (id, name) VALUES (0, 'pop r&b');
INSERT INTO GENRE (id, name) VALUES (0, 'progressive electro house');
INSERT INTO GENRE (id, name) VALUES (0, 'sertanejo');
INSERT INTO GENRE (id, name) VALUES (0, 'australian pop');
INSERT INTO GENRE (id, name) VALUES (0, 'toronto rap');
INSERT INTO GENRE (id, name) VALUES (0, 'puerto rican pop');
INSERT INTO GENRE (id, name) VALUES (0, 'sad rap');
INSERT INTO GENRE (id, name) VALUES (0, 'swedish pop');
INSERT INTO GENRE (id, name) VALUES (0, 'east coast hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'uk dance');
INSERT INTO GENRE (id, name) VALUES (0, 'electronica');
INSERT INTO GENRE (id, name) VALUES (0, 'rap metal');
INSERT INTO GENRE (id, name) VALUES (0, 'italian pop');
INSERT INTO GENRE (id, name) VALUES (0, 'indietronica');
INSERT INTO GENRE (id, name) VALUES (0, 'disco');
INSERT INTO GENRE (id, name) VALUES (0, 'modern bollywood');
INSERT INTO GENRE (id, name) VALUES (0, 'talent show');
INSERT INTO GENRE (id, name) VALUES (0, 'world worship');
INSERT INTO GENRE (id, name) VALUES (0, 'ccm');
INSERT INTO GENRE (id, name) VALUES (0, 'uk hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'punk');
INSERT INTO GENRE (id, name) VALUES (0, 'sertanejo pop');
INSERT INTO GENRE (id, name) VALUES (0, 'hoerspiel');
INSERT INTO GENRE (id, name) VALUES (0, 'brooklyn drill');
INSERT INTO GENRE (id, name) VALUES (0, 'mpb');
INSERT INTO GENRE (id, name) VALUES (0, 'turkish pop');
INSERT INTO GENRE (id, name) VALUES (0, 'glam rock');
INSERT INTO GENRE (id, name) VALUES (0, 'christian music');
INSERT INTO GENRE (id, name) VALUES (0, 'escape room');
INSERT INTO GENRE (id, name) VALUES (0, 'canadian contemporary r&b');
INSERT INTO GENRE (id, name) VALUES (0, 'cali rap');
INSERT INTO GENRE (id, name) VALUES (0, 'metropopolis');
INSERT INTO GENRE (id, name) VALUES (0, 'k-pop girl group');
INSERT INTO GENRE (id, name) VALUES (0, 'corridos tumbados');
INSERT INTO GENRE (id, name) VALUES (0, 'alternative dance');
INSERT INTO GENRE (id, name) VALUES (0, 'bedroom pop');
INSERT INTO GENRE (id, name) VALUES (0, 'social media pop');
INSERT INTO GENRE (id, name) VALUES (0, 'indonesian pop');
INSERT INTO GENRE (id, name) VALUES (0, 'hollywood');
INSERT INTO GENRE (id, name) VALUES (0, 'dark trap');
INSERT INTO GENRE (id, name) VALUES (0, 'otacore');
INSERT INTO GENRE (id, name) VALUES (0, 'brill building pop');
INSERT INTO GENRE (id, name) VALUES (0, 'rap francais');
INSERT INTO GENRE (id, name) VALUES (0, 'worship');
INSERT INTO GENRE (id, name) VALUES (0, 'argentine rock');
INSERT INTO GENRE (id, name) VALUES (0, 'emo');
INSERT INTO GENRE (id, name) VALUES (0, 'hardcore hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'filmi');
INSERT INTO GENRE (id, name) VALUES (0, 'heartland rock');
INSERT INTO GENRE (id, name) VALUES (0, 'indie cafe pop');
INSERT INTO GENRE (id, name) VALUES (0, 'pagode');
INSERT INTO GENRE (id, name) VALUES (0, 'pop nacional');
INSERT INTO GENRE (id, name) VALUES (0, 'metalcore');
INSERT INTO GENRE (id, name) VALUES (0, 'detroit hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'rap conscient');
INSERT INTO GENRE (id, name) VALUES (0, 'west coast rap');
INSERT INTO GENRE (id, name) VALUES (0, 'rap rock');
INSERT INTO GENRE (id, name) VALUES (0, 'piano rock');
INSERT INTO GENRE (id, name) VALUES (0, 'new americana');
INSERT INTO GENRE (id, name) VALUES (0, 'bolero');
INSERT INTO GENRE (id, name) VALUES (0, 'folk-pop');
INSERT INTO GENRE (id, name) VALUES (0, 'sleep');
INSERT INTO GENRE (id, name) VALUES (0, 'vapor soul');
INSERT INTO GENRE (id, name) VALUES (0, 'acoustic pop');
INSERT INTO GENRE (id, name) VALUES (0, 'vocal jazz');
INSERT INTO GENRE (id, name) VALUES (0, 'alternative hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'yacht rock');
INSERT INTO GENRE (id, name) VALUES (0, 'francoton');
INSERT INTO GENRE (id, name) VALUES (0, 'new rave');
INSERT INTO GENRE (id, name) VALUES (0, 'christian alternative rock');
INSERT INTO GENRE (id, name) VALUES (0, 'soundtrack');
INSERT INTO GENRE (id, name) VALUES (0, 'background music');
INSERT INTO GENRE (id, name) VALUES (0, 'show tunes');
INSERT INTO GENRE (id, name) VALUES (0, 'brazilian hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'turkish rock');
INSERT INTO GENRE (id, name) VALUES (0, 'lgbtq+ hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'dirty south rap');
INSERT INTO GENRE (id, name) VALUES (0, 'classical');
INSERT INTO GENRE (id, name) VALUES (0, 'british invasion');
INSERT INTO GENRE (id, name) VALUES (0, 'lounge');
INSERT INTO GENRE (id, name) VALUES (0, 'brazilian edm');
INSERT INTO GENRE (id, name) VALUES (0, 'trap argentino');
INSERT INTO GENRE (id, name) VALUES (0, 'cantautor');
INSERT INTO GENRE (id, name) VALUES (0, 'disco house');
INSERT INTO GENRE (id, name) VALUES (0, 'opm');
INSERT INTO GENRE (id, name) VALUES (0, 'j-rock');
INSERT INTO GENRE (id, name) VALUES (0, 'chillhop');
INSERT INTO GENRE (id, name) VALUES (0, 'indie anthem-folk');
INSERT INTO GENRE (id, name) VALUES (0, 'dutch pop');
INSERT INTO GENRE (id, name) VALUES (0, 'glam metal');
INSERT INTO GENRE (id, name) VALUES (0, 'dutch hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'trap queen');
INSERT INTO GENRE (id, name) VALUES (0, 'melodic metalcore');
INSERT INTO GENRE (id, name) VALUES (0, 'perreo');
INSERT INTO GENRE (id, name) VALUES (0, 'dfw rap');
INSERT INTO GENRE (id, name) VALUES (0, 'beatlesque');
INSERT INTO GENRE (id, name) VALUES (0, 'classic soul');
INSERT INTO GENRE (id, name) VALUES (0, 'north carolina hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'italian arena pop');
INSERT INTO GENRE (id, name) VALUES (0, 'country pop');
INSERT INTO GENRE (id, name) VALUES (0, 'synthpop');
INSERT INTO GENRE (id, name) VALUES (0, 'indiecoustica');
INSERT INTO GENRE (id, name) VALUES (0, 'forro');
INSERT INTO GENRE (id, name) VALUES (0, 'russian hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'brostep');
INSERT INTO GENRE (id, name) VALUES (0, 'brazilian rock');
INSERT INTO GENRE (id, name) VALUES (0, 'deep house');
INSERT INTO GENRE (id, name) VALUES (0, 'new french touch');
INSERT INTO GENRE (id, name) VALUES (0, 'rock-and-roll');
INSERT INTO GENRE (id, name) VALUES (0, 'nova mpb');
INSERT INTO GENRE (id, name) VALUES (0, 'funk metal');
INSERT INTO GENRE (id, name) VALUES (0, 'viral rap');
INSERT INTO GENRE (id, name) VALUES (0, 'german dance');
INSERT INTO GENRE (id, name) VALUES (0, 'polish hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'anthem worship');
INSERT INTO GENRE (id, name) VALUES (0, 'british soul');
INSERT INTO GENRE (id, name) VALUES (0, 'la indie');
INSERT INTO GENRE (id, name) VALUES (0, 'melancholia');
INSERT INTO GENRE (id, name) VALUES (0, 'new jack swing');
INSERT INTO GENRE (id, name) VALUES (0, 'garage rock');
INSERT INTO GENRE (id, name) VALUES (0, 'trap espanol');
INSERT INTO GENRE (id, name) VALUES (0, 'electronic trap');
INSERT INTO GENRE (id, name) VALUES (0, 'argentine hip hop');
INSERT INTO GENRE (id, name) VALUES (0, 'lilith');
INSERT INTO GENRE (id, name) VALUES (0, 'baroque pop');
INSERT INTO GENRE (id, name) VALUES (0, 'mandopop');
INSERT INTO GENRE (id, name) VALUES (0, 'bass trap');
INSERT INTO GENRE (id, name) VALUES (0, 'dance-punk');
INSERT INTO GENRE (id, name) VALUES (0, 'scorecore');
INSERT INTO GENRE (id, name) VALUES (0, 'kleine hoerspiel');
INSERT INTO GENRE (id, name) VALUES (0, 'german rock');
INSERT INTO GENRE (id, name) VALUES (0, 'mexican rock');
INSERT INTO GENRE (id, name) VALUES (0, 'deep big room');
INSERT INTO GENRE (id, name) VALUES (0, 'funk ostentacao');
INSERT INTO GENRE (id, name) VALUES (0, 'eurodance');